export const SEEDS4 = [
// ---- Men's Health ----
["Manforce 50","Sildenafil 50mg","Mankind Pharma","mens",105,1,"Strip of 4 tablets"],
["Megalis 10","Tadalafil 10mg","Macleods Pharmaceuticals","mens",205,1,"Strip of 4 tablets"],
["Tentex Forte","Ayurvedic Vitality Formula","Himalaya Wellness","mens",180,0,"Bottle of 100 tablets"],
["Confido","Ayurvedic Wellness Formula","Himalaya Wellness","mens",130,0,"Bottle of 60 tablets"],
["Speman","Ayurvedic Reproductive Wellness","Himalaya Wellness","mens",145,0,"Bottle of 60 tablets"],
["Addyzoa","Ayurvedic Fertility Support","Charak Pharma","mens",190,0,"Strip of 20 capsules"],
["Finax 1mg","Finasteride 1mg","Dr Reddy's Laboratories","mens",130,1,"Strip of 30 tablets"],
["Mintop 5% Solution","Minoxidil 5%","Dr Reddy's Laboratories","mens",680,0,"Bottle of 60ml solution"],
["Tugain 5% Solution","Minoxidil 5%","Cipla","mens",790,0,"Bottle of 60ml solution"],
// ---- Baby & Child Care ----
["Calpol 250 Suspension","Paracetamol 250mg/5ml","GSK","children",42,0,"Bottle of 60ml suspension"],
["Crocin DS Suspension","Paracetamol 240mg/5ml","GSK","children",58,0,"Bottle of 60ml suspension"],
["Dolo 250 Suspension","Paracetamol 250mg/5ml","Micro Labs","children",45,0,"Bottle of 60ml suspension"],
["Ibugesic Plus Suspension","Ibuprofen + Paracetamol","Cipla","children",42,0,"Bottle of 60ml suspension"],
["Meftal-P Suspension","Mefenamic Acid 100mg/5ml","Blue Cross Laboratories","children",40,0,"Bottle of 60ml suspension"],
["Junior Lanzol 15","Lansoprazole 15mg Dispersible","Cipla","children",85,1,"Strip of 15 tablets"],
["Ondem Syrup","Ondansetron 2mg/5ml","Alkem Laboratories","children",38,1,"Bottle of 30ml syrup"],
["Zifi 50 Dry Syrup","Cefixime 50mg/5ml","FDC Limited","children",78,1,"Bottle of 30ml suspension"],
["Azithral 200 Liquid","Azithromycin 200mg/5ml","Alembic Pharmaceuticals","children",68,1,"Bottle of 15ml suspension"],
["Ambrodil-S Syrup","Ambroxol + Salbutamol","Aristo Pharmaceuticals","children",45,1,"Bottle of 60ml syrup"],
["T-Minic Drops","Phenylephrine + CPM","Haleon","children",58,0,"Bottle of 15ml drops"],
["Zincovit Drops","Multivitamin + Zinc Drops","Apex Laboratories","children",65,0,"Bottle of 15ml drops"],
["Zincovit Syrup","Multivitamin + Zinc","Apex Laboratories","children",90,0,"Bottle of 200ml syrup"],
["Colicaid Drops","Simethicone + Dill Oil + Fennel Oil","Meyer Organics","children",55,0,"Bottle of 15ml drops"],
["Woodward's Gripe Water","Gripe Water","Wanbury","children",65,0,"Bottle of 130ml"],
["Bonnisan Liquid","Ayurvedic Digestive Tonic","Himalaya Wellness","children",92,0,"Bottle of 120ml liquid"],
["Pedialyte Classic","Oral Electrolyte Solution","Abbott","children",95,0,"Bottle of 200ml solution"],
["Pediasure Vanilla","Complete Kids Nutrition Powder","Abbott","children",660,0,"Jar of 400g powder"],
["Junior Horlicks","Kids Health Drink","Hindustan Unilever","children",280,0,"Jar of 500g powder"],
// ---- Bone, Joint & Muscle ----
["Volini Spray","Diclofenac Pain Relief Spray","Sun Pharma","ortho",280,0,"Can of 100g spray"],
["Volini Gel","Diclofenac Diethylamine Gel","Sun Pharma","ortho",165,0,"Tube of 50g gel"],
["Moov Spray","Ayurvedic Pain Relief Spray","Reckitt","ortho",245,0,"Can of 80g spray"],
["Moov Cream","Ayurvedic Pain Relief Cream","Reckitt","ortho",130,0,"Tube of 50g cream"],
["Iodex Balm","Multi-purpose Pain Balm","Haleon","ortho",135,0,"Jar of 40g balm"],
["Omnigel","Diclofenac Gel","Cipla","ortho",120,0,"Tube of 30g gel"],
["Dynapar QPS","Diclofenac Topical Solution","Troikaa Pharmaceuticals","ortho",165,0,"Bottle of 30ml solution"],
["Relispray","Instant Pain Relief Spray","Midas Care","ortho",260,0,"Can of 150g spray"],
["Zandu Balm","Herbal Pain Balm","Emami","ortho",55,0,"Jar of 25ml balm"],
["Amrutanjan Strong","Herbal Pain Balm","Amrutanjan Health Care","ortho",60,0,"Jar of 30g balm"],
["Tiger Balm Red","Herbal Pain Relief Ointment","Haw Par Healthcare","ortho",95,0,"Jar of 21ml balm"],
["Myoril 4","Thiocolchicoside 4mg","Sanofi","ortho",280,1,"Strip of 10 capsules"],
["Chymoral Forte","Trypsin-Chymotrypsin 100000AU","Torrent Pharmaceuticals","ortho",360,1,"Strip of 20 tablets"],
["Shallaki","Boswellia Serrata Extract","Himalaya Wellness","ortho",175,0,"Bottle of 60 tablets"],
["Rumalaya Forte","Ayurvedic Joint Care","Himalaya Wellness","ortho",185,0,"Bottle of 60 tablets"],
// ---- Neurology & Migraine ----
["Gabapin 300","Gabapentin 300mg","Intas Pharmaceuticals","neuro",315,1,"Strip of 15 capsules"],
["Gabapin-NT 100","Gabapentin 100mg + Nortriptyline 10mg","Intas Pharmaceuticals","neuro",250,1,"Strip of 15 tablets"],
["Pregeb 75","Pregabalin 75mg","Torrent Pharmaceuticals","neuro",170,1,"Strip of 10 capsules"],
["Levipil 500","Levetiracetam 500mg","Sun Pharma","neuro",105,1,"Strip of 10 tablets"],
["Encorate Chrono 300","Sodium Valproate CR 300mg","Sun Pharma","neuro",85,1,"Strip of 10 tablets"],
["Eptoin 100","Phenytoin 100mg","Abbott","neuro",145,1,"Bottle of 120 tablets"],
["Vertin 16","Betahistine 16mg","Abbott","neuro",280,1,"Strip of 15 tablets"],
["Stugeron 25","Cinnarizine 25mg","Janssen","neuro",65,1,"Strip of 20 tablets"],
["Naxdom 500","Naproxen 500mg + Domperidone 10mg","Sun Pharma","neuro",175,1,"Strip of 10 tablets"],
["Suminat 50","Sumatriptan 50mg","Sun Pharma","neuro",160,1,"Strip of 1 tablet"],
["Vasograin","Ergotamine + Caffeine + Paracetamol + Prochlorperazine","Cadila Pharmaceuticals","neuro",95,1,"Strip of 10 tablets"],
["Sibelium 10","Flunarizine 10mg","Janssen","neuro",305,1,"Strip of 10 tablets"],
["Donep 5","Donepezil 5mg","Alkem Laboratories","neuro",95,1,"Strip of 10 tablets"],
["Meloset 3","Melatonin 3mg","Aristo Pharmaceuticals","neuro",65,0,"Strip of 10 tablets"],
// ---- Liver & Kidney Care ----
["Liv.52 Tablets","Ayurvedic Liver Tonic","Himalaya Wellness","liver-kidney",130,0,"Bottle of 100 tablets"],
["Liv.52 DS","Double Strength Liver Care","Himalaya Wellness","liver-kidney",165,0,"Bottle of 60 tablets"],
["Udiliv 300","Ursodeoxycholic Acid 300mg","Abbott","liver-kidney",560,1,"Strip of 15 tablets"],
["Ursocol 300","Ursodeoxycholic Acid 300mg","Sun Pharma","liver-kidney",480,1,"Strip of 10 tablets"],
["Hepamerz Granules","L-Ornithine L-Aspartate","Win-Medicare","liver-kidney",420,1,"Pack of 5 sachets"],
["Cystone","Ayurvedic Urinary Stone Support","Himalaya Wellness","liver-kidney",140,0,"Bottle of 60 tablets"],
["Neeri Tablets","Ayurvedic Urinary Wellness","Aimil Pharmaceuticals","liver-kidney",150,0,"Bottle of 30 tablets"],
["Chandraprabha Vati","Classical Ayurvedic Formula","Baidyanath","liver-kidney",130,0,"Bottle of 80 tablets"],
["Alkasol Syrup","Disodium Hydrogen Citrate","Stadmed","liver-kidney",145,0,"Bottle of 100ml syrup"],
["Cital Syrup","Urinary Alkalizer","Indoco Remedies","liver-kidney",120,0,"Bottle of 100ml syrup"],
["Nodosis 500","Sodium Bicarbonate 500mg","Alkem Laboratories","liver-kidney",85,1,"Strip of 10 tablets"],
// ---- Thyroid & Hormonal ----
["Thyronorm 25","Thyroxine Sodium 25mcg","Abbott","thyroid",125,1,"Bottle of 120 tablets"],
["Thyronorm 50","Thyroxine Sodium 50mcg","Abbott","thyroid",145,1,"Bottle of 120 tablets"],
["Thyronorm 75","Thyroxine Sodium 75mcg","Abbott","thyroid",165,1,"Bottle of 120 tablets"],
["Thyronorm 100","Thyroxine Sodium 100mcg","Abbott","thyroid",180,1,"Bottle of 120 tablets"],
["Eltroxin 50","Thyroxine Sodium 50mcg","GSK","thyroid",130,1,"Bottle of 100 tablets"],
["Eltroxin 100","Thyroxine Sodium 100mcg","GSK","thyroid",155,1,"Bottle of 100 tablets"],
["Thyrox 50","Thyroxine Sodium 50mcg","Macleods Pharmaceuticals","thyroid",120,1,"Bottle of 100 tablets"],
["Thyrox 100","Thyroxine Sodium 100mcg","Macleods Pharmaceuticals","thyroid",140,1,"Bottle of 100 tablets"],
["Neomercazole 5","Carbimazole 5mg","Abbott","thyroid",145,1,"Bottle of 30 tablets"],
// ---- Dental & Oral Care ----
["Hexigel","Chlorhexidine Gluconate 1%","ICPA Health Products","dental",75,0,"Tube of 15g gel"],
["Hiora-SG Gel","Ayurvedic Mouth Gel","Himalaya Wellness","dental",80,0,"Tube of 10g gel"],
["Dologel CT","Choline Salicylate + Lidocaine","Dr Reddy's Laboratories","dental",95,0,"Tube of 10g gel"],
["Mucopain Gel","Benzocaine 20%","ICPA Health Products","dental",58,0,"Tube of 15g gel"],
["Zytee RB Gel","Choline Salicylate + Benzalkonium","Raptakos Brett","dental",55,0,"Tube of 10ml gel"],
["Clohex Plus Mouthwash","Chlorhexidine + Zinc","Dr Reddy's Laboratories","dental",160,0,"Bottle of 150ml mouthwash"],
["Hexidine Mouthwash","Chlorhexidine Gluconate 0.2%","ICPA Health Products","dental",110,0,"Bottle of 160ml mouthwash"],
["Senquel-AD Toothpaste","Desensitizing Fluoride Toothpaste","Dr Reddy's Laboratories","dental",130,0,"Tube of 100g paste"],
["Thermoseal RA Toothpaste","Sensitive Teeth Toothpaste","ICPA Health Products","dental",110,0,"Tube of 100g paste"],
["Sensodyne Rapid Relief","Sensitivity Relief Toothpaste","Haleon","dental",155,0,"Tube of 80g paste"],
// ---- Ayurvedic & Herbal ----
["Dabur Chyawanprash","Classical Immunity Formula","Dabur","ayurvedic",340,0,"Jar of 500g"],
["Himalaya Guduchi","Giloy Immunity Tablets","Himalaya Wellness","ayurvedic",150,0,"Bottle of 60 tablets"],
["Septilin Tablets","Ayurvedic Immunity Builder","Himalaya Wellness","ayurvedic",165,0,"Bottle of 60 tablets"],
["Ashwagandha Tablets","Withania Somnifera Extract","Himalaya Wellness","ayurvedic",165,0,"Bottle of 60 tablets"],
["Brahmi Tablets","Bacopa Monnieri Extract","Himalaya Wellness","ayurvedic",150,0,"Bottle of 60 tablets"],
["Triphala Tablets","Classical Digestive Formula","Himalaya Wellness","ayurvedic",150,0,"Bottle of 60 tablets"],
["Neem Tablets","Azadirachta Indica Extract","Himalaya Wellness","ayurvedic",140,0,"Bottle of 60 tablets"],
["Giloy Ghanvati","Giloy Stem Extract","Patanjali Ayurved","ayurvedic",90,0,"Bottle of 60 tablets"],
["Divya Madhunashini Vati","Ayurvedic Sugar Management","Patanjali Ayurved","ayurvedic",180,0,"Bottle of 120 tablets"],
["Triphala Churna","Digestive Herbal Powder","Patanjali Ayurved","ayurvedic",75,0,"Pack of 100g powder"],
["Pudin Hara Pearls","Pudina Digestive Capsules","Dabur","ayurvedic",42,0,"Strip of 10 capsules"],
["Hajmola Regular","Digestive Tablets","Dabur","ayurvedic",48,0,"Bottle of 120 tablets"],
["Kayam Churna","Herbal Laxative Powder","Sheth Brothers","ayurvedic",95,0,"Pack of 100g powder"],
["Dabur Isabgol","Psyllium Husk Fibre","Dabur","ayurvedic",145,0,"Pack of 100g"],
["Safi Syrup","Herbal Blood Purifier","Hamdard","ayurvedic",140,0,"Bottle of 200ml syrup"],
["Ashokarishta","Classical Women's Tonic","Baidyanath","ayurvedic",150,0,"Bottle of 450ml tonic"],
["Dashmularishta","Classical Restorative Tonic","Baidyanath","ayurvedic",160,0,"Bottle of 450ml tonic"],
["Sitopaladi Churna","Respiratory Herbal Powder","Baidyanath","ayurvedic",110,0,"Pack of 60g powder"],
["Mahanarayan Tail","Joint Massage Oil","Baidyanath","ayurvedic",140,0,"Bottle of 100ml oil"],
["Honitus Syrup","Herbal Cough Remedy","Dabur","ayurvedic",105,0,"Bottle of 100ml syrup"],
["Koflet Syrup","Herbal Cough Formula","Himalaya Wellness","ayurvedic",95,0,"Bottle of 100ml syrup"],
["Dabur Tulsi Drops","Panch Tulsi Extract","Dabur","ayurvedic",105,0,"Bottle of 30ml drops"],
["Immusante","Ayurvedic Immunity Support","Himalaya Wellness","ayurvedic",175,0,"Bottle of 60 tablets"],
// ---- First Aid & OTC Essentials ----
["Betadine 10% Solution","Povidone Iodine 10%","Win-Medicare","firstaid",120,0,"Bottle of 100ml solution"],
["Betadine Ointment","Povidone Iodine 5%","Win-Medicare","firstaid",105,0,"Tube of 20g ointment"],
["Dettol Antiseptic Liquid","Chloroxylenol 4.8%","Reckitt","firstaid",115,0,"Bottle of 210ml liquid"],
["Savlon Antiseptic Liquid","Chlorhexidine + Cetrimide","ITC","firstaid",95,0,"Bottle of 200ml liquid"],
["Suthol Antiseptic Spray","Neem + Antiseptic Skin Spray","GD Pharmaceuticals","firstaid",110,0,"Bottle of 100ml spray"],
["Burnol Cream","Aminacrine + Cetrimide Burn Cream","Dr Morepen","firstaid",85,0,"Tube of 20g cream"],
["Band-Aid Washproof","Adhesive Wound Strips","Kenvue","firstaid",75,0,"Pack of 20 strips"],
["Hansaplast Corn Caps","Salicylic Acid Corn Plasters","Beiersdorf","firstaid",55,0,"Pack of 9 plasters"],
["Krack Cream","Heel Crack Repair Cream","Reckitt","firstaid",85,0,"Tube of 25g cream"],
["Electral Powder","WHO ORS Formula Sachet","FDC Limited","firstaid",22,0,"Sachet of 21.8g"],
["Enerzal Powder","Energy + Electrolyte Drink Mix","FDC Limited","firstaid",180,0,"Jar of 500g powder"],
["ORSL Electrolyte Drink Apple","Ready-to-drink Electrolytes","Kenvue","firstaid",40,0,"Tetra pack of 200ml"],
["Glucon-D Original","Glucose Energy Powder","Zydus Wellness","firstaid",130,0,"Jar of 450g powder"],
["Nycil Classic","Prickly Heat Powder","Zydus Wellness","firstaid",110,0,"Bottle of 150g powder"],
["Dermicool Powder","Prickly Heat Cooling Powder","Reckitt","firstaid",105,0,"Bottle of 150g powder"],
["Nicotex 2mg","Nicotine Gum","Cipla","firstaid",165,0,"Pack of 9 gums"],
["Accu-Chek Active Strips","Blood Glucose Test Strips","Roche Diabetes Care","firstaid",925,0,"Box of 50 strips"],
["Dr Morepen Gluco One Strips","Blood Glucose Test Strips","Dr Morepen","firstaid",599,0,"Box of 50 strips"],
// ---- General Wellness & Nutrition ----
["Ensure Vanilla","Complete Adult Nutrition Powder","Abbott","wellness",720,0,"Jar of 400g powder"],
["Protinex Original","Protein Supplement Powder","Danone","wellness",645,0,"Jar of 400g powder"],
["B-Protin Vanilla","Balanced Protein Powder","British Biologicals","wellness",540,0,"Jar of 400g powder"],
["Horlicks Classic Malt","Health Drink Powder","Hindustan Unilever","wellness",270,0,"Jar of 500g powder"],
["Threptin Diskettes","High Protein Biscuits","Raptakos Brett","wellness",380,0,"Pack of 275g"],
["Endura Mass","Weight Gain Supplement","Medinn Belle","wellness",560,0,"Jar of 400g powder"],
["Dabur Honey","Pure Natural Honey","Dabur","wellness",220,0,"Bottle of 500g"],
["Patanjali Honey","Pure Natural Honey","Patanjali Ayurved","wellness",180,0,"Bottle of 500g"],
["Organic India Tulsi Green Tea","Herbal Green Tea","Organic India","wellness",180,0,"Box of 25 tea bags"]
];
