export const SEEDS3 = [
// ---- Cold, Cough & Respiratory ----
["Montair LC","Montelukast 10mg + Levocetirizine 5mg","Cipla","respiratory",265,1,"Strip of 15 tablets"],
["Montek LC","Montelukast 10mg + Levocetirizine 5mg","Sun Pharma","respiratory",262,1,"Strip of 15 tablets"],
["Montina-L","Montelukast 10mg + Levocetirizine 5mg","Aristo Pharmaceuticals","respiratory",180,1,"Strip of 10 tablets"],
["Asthalin 100 Inhaler","Salbutamol 100mcg","Cipla","respiratory",165,1,"Inhaler of 200 doses"],
["Asthalin Syrup","Salbutamol 2mg/5ml","Cipla","respiratory",22,1,"Bottle of 100ml syrup"],
["Levolin Inhaler","Levosalbutamol 50mcg","Cipla","respiratory",220,1,"Inhaler of 200 doses"],
["Budecort 200 Inhaler","Budesonide 200mcg","Cipla","respiratory",440,1,"Inhaler of 200 doses"],
["Budecort 0.5 Respules","Budesonide 0.5mg","Cipla","respiratory",180,1,"Pack of 5 respules"],
["Foracort 200 Inhaler","Formoterol 6mcg + Budesonide 200mcg","Cipla","respiratory",590,1,"Inhaler of 120 doses"],
["Seroflo 250 Inhaler","Salmeterol 25mcg + Fluticasone 250mcg","Cipla","respiratory",595,1,"Inhaler of 120 doses"],
["Duolin Respules","Levosalbutamol + Ipratropium","Cipla","respiratory",105,1,"Pack of 5x2.5ml respules"],
["Ascoril LS Syrup","Levosalbutamol + Ambroxol + Guaifenesin","Glenmark Pharmaceuticals","respiratory",132,1,"Bottle of 100ml syrup"],
["Ascoril D Plus","Dextromethorphan + Phenylephrine + CPM","Glenmark Pharmaceuticals","respiratory",130,0,"Bottle of 100ml syrup"],
["Grilinctus Syrup","Dextromethorphan + Chlorpheniramine","Franco-Indian Pharmaceuticals","respiratory",105,0,"Bottle of 100ml syrup"],
["Chericof Syrup","Dextromethorphan + Phenylephrine + CPM","Sun Pharma","respiratory",110,0,"Bottle of 100ml syrup"],
["Alex Syrup","Phenylephrine + CPM + Dextromethorphan","Glenmark Pharmaceuticals","respiratory",108,0,"Bottle of 100ml syrup"],
["Benadryl Cough Formula","Diphenhydramine + Ammonium Chloride","Kenvue","respiratory",130,0,"Bottle of 150ml syrup"],
["Torex Syrup","Codeine-free Cough Formula","Torque Pharmaceuticals","respiratory",95,0,"Bottle of 100ml syrup"],
["Zedex Syrup","Bromhexine + Dextromethorphan","Wockhardt","respiratory",105,0,"Bottle of 100ml syrup"],
["Sinarest","Paracetamol + Phenylephrine + CPM","Centaur Pharmaceuticals","respiratory",68,0,"Strip of 10 tablets"],
["Cheston Cold","Cetirizine + Phenylephrine + Paracetamol","Cipla","respiratory",55,0,"Strip of 10 tablets"],
["Solvin Cold","Phenylephrine + CPM + Paracetamol","Ipca Laboratories","respiratory",48,0,"Strip of 10 tablets"],
["Wikoryl","Paracetamol + Phenylephrine + CPM","Alembic Pharmaceuticals","respiratory",52,0,"Strip of 10 tablets"],
["D'Cold Total","Paracetamol + Phenylephrine + Caffeine","Reckitt","respiratory",40,0,"Strip of 10 tablets"],
["Coldact","Phenylephrine + Chlorpheniramine","Sun Pharma","respiratory",45,0,"Strip of 10 capsules"],
["Febrex Plus","Paracetamol + Phenylephrine + CPM","Indoco Remedies","respiratory",45,0,"Strip of 15 tablets"],
["Vicks Action 500 Advanced","Paracetamol + Phenylephrine + Caffeine","P&G","respiratory",38,0,"Strip of 10 tablets"],
["Otrivin Adult Nasal Spray","Xylometazoline 0.1%","Haleon","respiratory",105,0,"Bottle of 10ml spray"],
["Otrivin Paediatric Drops","Xylometazoline 0.05%","Haleon","respiratory",85,0,"Bottle of 10ml drops"],
["Nasivion Adult Spray","Oxymetazoline 0.05%","P&G Health","respiratory",92,0,"Bottle of 10ml spray"],
["Nasoclear Saline Spray","Sodium Chloride 0.65%","Cipla","respiratory",105,0,"Bottle of 20ml spray"],
["Vicks VapoRub","Menthol + Camphor + Eucalyptus","P&G","respiratory",155,0,"Jar of 50g balm"],
["Vicks Inhaler","Menthol + Camphor Nasal Stick","P&G","respiratory",45,0,"Pack of 1 inhaler stick"],
["Cofsils Lozenges","Amylmetacresol + Dichlorobenzyl Alcohol","Cipla","respiratory",55,0,"Strip of 10 lozenges"],
["Strepsils Orange","Amylmetacresol Lozenges","Reckitt","respiratory",50,0,"Strip of 8 lozenges"],
["Karvol Plus Capsules","Menthol + Camphor Inhalant","Zydus Lifesciences","respiratory",68,0,"Strip of 10 capsules"],
// ---- Allergy Care ----
["Cetzine 10","Cetirizine 10mg","Dr Reddy's Laboratories","allergy",30,0,"Strip of 10 tablets"],
["Okacet 10","Cetirizine 10mg","Cipla","allergy",18,0,"Strip of 10 tablets"],
["Alerid 10","Cetirizine 10mg","Cipla","allergy",22,0,"Strip of 10 tablets"],
["Levocet 5","Levocetirizine 5mg","Hetero Healthcare","allergy",22,0,"Strip of 10 tablets"],
["Xyzal 5","Levocetirizine 5mg","UCB India","allergy",95,0,"Strip of 10 tablets"],
["Teczine 5","Levocetirizine 5mg","Sun Pharma","allergy",85,0,"Strip of 10 tablets"],
["Allegra 120","Fexofenadine 120mg","Sanofi","allergy",218,0,"Strip of 10 tablets"],
["Allegra 180","Fexofenadine 180mg","Sanofi","allergy",255,0,"Strip of 10 tablets"],
["Allegra-M","Fexofenadine 120mg + Montelukast 10mg","Sanofi","allergy",305,1,"Strip of 10 tablets"],
["Avil 25","Pheniramine Maleate 25mg","Sanofi","allergy",12,0,"Strip of 15 tablets"],
["Atarax 10","Hydroxyzine 10mg","Dr Reddy's Laboratories","allergy",72,1,"Strip of 15 tablets"],
["Ebast 10","Ebastine 10mg","Micro Labs","allergy",110,1,"Strip of 10 tablets"],
["Practin 4","Cyproheptadine 4mg","Wockhardt","allergy",25,0,"Strip of 20 tablets"],
["Omnacortil 10","Prednisolone 10mg","Macleods Pharmaceuticals","allergy",42,1,"Strip of 10 tablets"],
["Wysolone 5","Prednisolone 5mg","Pfizer","allergy",28,1,"Strip of 10 tablets"],
["Medrol 4","Methylprednisolone 4mg","Pfizer","allergy",78,1,"Strip of 14 tablets"],
["Dexona 0.5","Dexamethasone 0.5mg","Zydus Lifesciences","allergy",5,1,"Strip of 20 tablets"],
// ---- Skin Care ----
["Candid Cream","Clotrimazole 1%","Glenmark Pharmaceuticals","skin",95,0,"Tube of 20g cream"],
["Candid-B Cream","Clotrimazole + Beclometasone","Glenmark Pharmaceuticals","skin",125,1,"Tube of 20g cream"],
["Candid Dusting Powder","Clotrimazole 1%","Glenmark Pharmaceuticals","skin",145,0,"Bottle of 100g powder"],
["Nizral 2% Cream","Ketoconazole 2%","Johnson & Johnson","skin",180,0,"Tube of 30g cream"],
["Nizral 2% Shampoo","Ketoconazole 2%","Johnson & Johnson","skin",330,0,"Bottle of 50ml shampoo"],
["Terbicip 250","Terbinafine 250mg","Cipla","skin",150,1,"Strip of 7 tablets"],
["Canditral 100","Itraconazole 100mg","Glenmark Pharmaceuticals","skin",180,1,"Strip of 10 capsules"],
["Fluka 150","Fluconazole 150mg","Cipla","skin",18,1,"Strip of 1 tablet"],
["AF 150","Fluconazole 150mg","Systopic Laboratories","skin",30,1,"Strip of 1 tablet"],
["Betnovate-N","Betamethasone + Neomycin","GSK","skin",60,1,"Tube of 20g cream"],
["Betnovate-C","Betamethasone + Clioquinol","GSK","skin",65,1,"Tube of 20g cream"],
["Quadriderm RF","Beclometasone + Gentamicin + Tolnaftate + Clioquinol","Zydus Lifesciences","skin",130,1,"Tube of 20g cream"],
["Soframycin Skin Cream","Framycetin 1%","Sanofi","skin",58,0,"Tube of 30g cream"],
["Neosporin Powder","Neomycin + Bacitracin + Polymyxin B","GSK","skin",98,0,"Bottle of 10g powder"],
["T-Bact Ointment","Mupirocin 2%","GSK","skin",265,1,"Tube of 5g ointment"],
["Acnestar Gel","Clindamycin + Nicotinamide","Mankind Pharma","skin",120,0,"Tube of 22g gel"],
["Persol 5% Gel","Benzoyl Peroxide 5%","Wallace Pharmaceuticals","skin",85,0,"Tube of 30g gel"],
["Retino-A 0.025% Cream","Tretinoin 0.025%","Johnson & Johnson","skin",175,1,"Tube of 20g cream"],
["Saslic DS Face Wash","Salicylic Acid 2%","Cipla","skin",360,0,"Bottle of 60ml face wash"],
["Suncros Aqua Gel SPF 50","Broad Spectrum Sunscreen","Sun Pharma","skin",625,0,"Tube of 50g gel"],
["Cetaphil Gentle Skin Cleanser","Mild Non-soap Cleanser","Galderma","skin",450,0,"Bottle of 125ml cleanser"],
["Venusia Max Lotion","Intensive Moisturizer","Dr Reddy's Laboratories","skin",525,0,"Bottle of 300ml lotion"],
["Moisturex Soft Cream","Urea + Glycerin + Lactic Acid","Sun Pharma","skin",280,0,"Tube of 60g cream"],
["Elovera Cream","Aloe Vera + Vitamin E","Glenmark Pharmaceuticals","skin",280,0,"Tube of 75g cream"],
["Tedibar Soap","Syndet Bar for Sensitive Skin","Torrent Pharmaceuticals","skin",165,0,"Bar of 75g"],
["Lacto Calamine Lotion","Calamine + Kaolin","Piramal Pharma","skin",165,0,"Bottle of 120ml lotion"],
["Boroline","Antiseptic Perfumed Cream","GD Pharmaceuticals","skin",65,0,"Tube of 20g cream"],
["BoroPlus","Antiseptic Ayurvedic Cream","Emami","skin",75,0,"Tube of 40g cream"],
["Itch Guard Plus","Antifungal Cream","Reckitt","skin",90,0,"Tube of 20g cream"],
["Ring Guard","Miconazole Antifungal Cream","Reckitt","skin",82,0,"Tube of 20g cream"],
["Permite 5% Cream","Permethrin 5%","Galderma","skin",140,0,"Tube of 30g cream"],
["Melaglow Rich Cream","Skin Brightening Complex","Abbott","skin",350,0,"Tube of 20g cream"],
// ---- Eye & Ear Care ----
["Refresh Tears","Carboxymethylcellulose 0.5%","Allergan India","eye-ear",165,0,"Bottle of 10ml eye drops"],
["Systane Ultra","Polyethylene Glycol Lubricant","Alcon","eye-ear",385,0,"Bottle of 10ml eye drops"],
["Genteal Eye Drops","Hypromellose 0.3%","Alcon","eye-ear",145,0,"Bottle of 10ml eye drops"],
["Eyemist Forte","Sodium Hyaluronate 0.3%","Sun Pharma","eye-ear",280,0,"Bottle of 10ml eye drops"],
["Itone Eye Drops","Herbal Eye Care Formula","Dey's Medical","eye-ear",85,0,"Bottle of 10ml eye drops"],
["Moxicip Eye Drops","Moxifloxacin 0.5%","Cipla","eye-ear",130,1,"Bottle of 5ml eye drops"],
["Ciplox Eye/Ear Drops","Ciprofloxacin 0.3%","Cipla","eye-ear",18,1,"Bottle of 10ml drops"],
["Toba Eye Drops","Tobramycin 0.3%","Sun Pharma","eye-ear",55,1,"Bottle of 5ml eye drops"],
["Winolap 0.1","Olopatadine 0.1%","Ajanta Pharma","eye-ear",150,1,"Bottle of 5ml eye drops"],
["Candibiotic Ear Drops","Chloramphenicol + Clotrimazole + Lidocaine","Glenmark Pharmaceuticals","eye-ear",118,1,"Bottle of 5ml ear drops"],
["Waxonil Ear Drops","Ear Wax Softening Drops","Alembic Pharmaceuticals","eye-ear",95,0,"Bottle of 10ml ear drops"],
// ---- Women's Health ----
["Susten 200","Micronized Progesterone 200mg","Sun Pharma","womens",420,1,"Strip of 10 capsules"],
["Duphaston 10","Dydrogesterone 10mg","Abbott","womens",620,1,"Strip of 10 tablets"],
["Meprate 10","Medroxyprogesterone 10mg","Serum Institute of India","womens",55,1,"Strip of 10 tablets"],
["Regestrone 5","Norethisterone 5mg","Torrent Pharmaceuticals","womens",58,1,"Strip of 10 tablets"],
["Primolut-N","Norethisterone 5mg","Bayer","womens",65,1,"Strip of 10 tablets"],
["Krimson 35","Ethinylestradiol + Cyproterone","Sun Pharma","womens",180,1,"Strip of 21 tablets"],
["Novelon","Ethinylestradiol + Desogestrel","MSD Pharmaceuticals","womens",155,1,"Strip of 21 tablets"],
["i-Pill","Levonorgestrel 1.5mg","Piramal Pharma","womens",110,0,"Strip of 1 tablet"],
["Unwanted 72","Levonorgestrel 1.5mg","Mankind Pharma","womens",105,0,"Strip of 1 tablet"],
["M2-Tone Syrup","Ayurvedic Uterine Tonic","Charak Pharma","womens",180,0,"Bottle of 200ml syrup"],
["Evecare Syrup","Ayurvedic Menstrual Wellness","Himalaya Wellness","womens",165,0,"Bottle of 200ml syrup"],
["Shatavari Tablets","Asparagus Racemosus Extract","Himalaya Wellness","womens",190,0,"Bottle of 60 tablets"],
["V Wash Plus","Intimate Hygiene Wash","Glenmark Pharmaceuticals","womens",180,0,"Bottle of 100ml wash"],
["Prega News","hCG Pregnancy Test Kit","Mankind Pharma","womens",55,0,"Pack of 1 test kit"]
];
