export const SEEDS2 = [
// ---- Heart & Blood Pressure ----
["Telma 40","Telmisartan 40mg","Glenmark Pharmaceuticals","cardiac",215,1,"Strip of 30 tablets"],
["Telma 20","Telmisartan 20mg","Glenmark Pharmaceuticals","cardiac",120,1,"Strip of 30 tablets"],
["Telma 80","Telmisartan 80mg","Glenmark Pharmaceuticals","cardiac",320,1,"Strip of 30 tablets"],
["Telma-H 40","Telmisartan 40mg + Hydrochlorothiazide 12.5mg","Glenmark Pharmaceuticals","cardiac",230,1,"Strip of 15 tablets"],
["Telmikind 40","Telmisartan 40mg","Mankind Pharma","cardiac",60,1,"Strip of 10 tablets"],
["Telsartan 40","Telmisartan 40mg","Dr Reddy's Laboratories","cardiac",188,1,"Strip of 15 tablets"],
["Tazloc 40","Telmisartan 40mg","USV","cardiac",150,1,"Strip of 15 tablets"],
["Losar 50","Losartan 50mg","Unichem Laboratories","cardiac",150,1,"Strip of 15 tablets"],
["Repace 50","Losartan 50mg","Sun Pharma","cardiac",95,1,"Strip of 15 tablets"],
["Olmezest 20","Olmesartan 20mg","Sun Pharma","cardiac",130,1,"Strip of 10 tablets"],
["Amlong 5","Amlodipine 5mg","Micro Labs","cardiac",52,1,"Strip of 15 tablets"],
["Amlong 10","Amlodipine 10mg","Micro Labs","cardiac",85,1,"Strip of 15 tablets"],
["Stamlo 5","Amlodipine 5mg","Dr Reddy's Laboratories","cardiac",38,1,"Strip of 15 tablets"],
["Amlokind-AT","Amlodipine 5mg + Atenolol 50mg","Mankind Pharma","cardiac",35,1,"Strip of 15 tablets"],
["Amlopres-AT","Amlodipine 5mg + Atenolol 50mg","Cipla","cardiac",70,1,"Strip of 15 tablets"],
["Cilacar 10","Cilnidipine 10mg","JB Chemicals","cardiac",180,1,"Strip of 15 tablets"],
["Cilacar 20","Cilnidipine 20mg","JB Chemicals","cardiac",280,1,"Strip of 15 tablets"],
["Cilacar-T","Cilnidipine 10mg + Telmisartan 40mg","JB Chemicals","cardiac",250,1,"Strip of 15 tablets"],
["Nebicard 5","Nebivolol 5mg","Torrent Pharmaceuticals","cardiac",165,1,"Strip of 15 tablets"],
["Nebistar 5","Nebivolol 5mg","Lupin","cardiac",155,1,"Strip of 15 tablets"],
["Metolar XR 50","Metoprolol Succinate XR 50mg","Cipla","cardiac",95,1,"Strip of 15 tablets"],
["Prolomet XL 50","Metoprolol Succinate XL 50mg","Sun Pharma","cardiac",105,1,"Strip of 15 tablets"],
["Concor 5","Bisoprolol 5mg","Merck","cardiac",140,1,"Strip of 10 tablets"],
["Aten 50","Atenolol 50mg","Zydus Lifesciences","cardiac",38,1,"Strip of 14 tablets"],
["Betacap TR 40","Propranolol TR 40mg","Sun Pharma","cardiac",78,1,"Strip of 10 capsules"],
["Cardace 5","Ramipril 5mg","Sanofi","cardiac",150,1,"Strip of 15 tablets"],
["Ecosprin 75","Aspirin 75mg","USV","cardiac",9,1,"Strip of 14 tablets"],
["Ecosprin 150","Aspirin 150mg","USV","cardiac",14,1,"Strip of 14 tablets"],
["Ecosprin-AV 75","Aspirin 75mg + Atorvastatin 10mg","USV","cardiac",105,1,"Strip of 10 capsules"],
["Clopitab 75","Clopidogrel 75mg","Lupin","cardiac",60,1,"Strip of 15 tablets"],
["Clopitab-A 75","Clopidogrel 75mg + Aspirin 75mg","Lupin","cardiac",110,1,"Strip of 10 capsules"],
["Deplatt 75","Clopidogrel 75mg","Torrent Pharmaceuticals","cardiac",55,1,"Strip of 15 tablets"],
["Deplatt-A 75","Clopidogrel 75mg + Aspirin 75mg","Torrent Pharmaceuticals","cardiac",100,1,"Strip of 10 tablets"],
["Axcer 90","Ticagrelor 90mg","Sun Pharma","cardiac",380,1,"Strip of 14 tablets"],
["Rosuvas 10","Rosuvastatin 10mg","Sun Pharma","cardiac",310,1,"Strip of 15 tablets"],
["Rosuvas 20","Rosuvastatin 20mg","Sun Pharma","cardiac",525,1,"Strip of 15 tablets"],
["Rosulip 10","Rosuvastatin 10mg","USV","cardiac",280,1,"Strip of 15 tablets"],
["Rosuvas F 10","Rosuvastatin 10mg + Fenofibrate 160mg","Sun Pharma","cardiac",390,1,"Strip of 15 tablets"],
["Atorva 10","Atorvastatin 10mg","Zydus Lifesciences","cardiac",90,1,"Strip of 15 tablets"],
["Atorva 40","Atorvastatin 40mg","Zydus Lifesciences","cardiac",190,1,"Strip of 15 tablets"],
["Storvas 20","Atorvastatin 20mg","Sun Pharma","cardiac",130,1,"Strip of 15 tablets"],
["Sorbitrate 5","Isosorbide Dinitrate 5mg","Abbott","cardiac",20,1,"Strip of 30 tablets"],
["Dytor 10","Torsemide 10mg","Cipla","cardiac",105,1,"Strip of 15 tablets"],
["Lasix 40","Furosemide 40mg","Sanofi","cardiac",12,1,"Strip of 15 tablets"],
// ---- Digestive Health ----
["Pan 40","Pantoprazole 40mg","Alkem Laboratories","gastro",145,1,"Strip of 15 tablets"],
["Pan 20","Pantoprazole 20mg","Alkem Laboratories","gastro",92,1,"Strip of 15 tablets"],
["Pan-D","Pantoprazole 40mg + Domperidone 30mg","Alkem Laboratories","gastro",199,1,"Strip of 15 capsules"],
["Pantocid 40","Pantoprazole 40mg","Sun Pharma","gastro",155,1,"Strip of 15 tablets"],
["Pantop 40","Pantoprazole 40mg","Aristo Pharmaceuticals","gastro",120,1,"Strip of 15 tablets"],
["Pantodac 40","Pantoprazole 40mg","Zydus Lifesciences","gastro",148,1,"Strip of 15 tablets"],
["Omez 20","Omeprazole 20mg","Dr Reddy's Laboratories","gastro",58,1,"Strip of 20 capsules"],
["Omez 40","Omeprazole 40mg","Dr Reddy's Laboratories","gastro",98,1,"Strip of 15 capsules"],
["Omez-D","Omeprazole 20mg + Domperidone 10mg","Dr Reddy's Laboratories","gastro",120,1,"Strip of 15 capsules"],
["Ocid 20","Omeprazole 20mg","Zydus Lifesciences","gastro",54,1,"Strip of 20 capsules"],
["Rablet 20","Rabeprazole 20mg","Lupin","gastro",130,1,"Strip of 15 tablets"],
["Razo 20","Rabeprazole 20mg","Dr Reddy's Laboratories","gastro",165,1,"Strip of 15 tablets"],
["Nexpro 40","Esomeprazole 40mg","Torrent Pharmaceuticals","gastro",150,1,"Strip of 15 tablets"],
["Nexpro RD 40","Esomeprazole 40mg + Domperidone 30mg","Torrent Pharmaceuticals","gastro",210,1,"Strip of 15 capsules"],
["Famocid 20","Famotidine 20mg","Sun Pharma","gastro",35,0,"Strip of 14 tablets"],
["Mucaine Gel Mint","Oxetacaine + Aluminium Hydroxide + Magnesium Hydroxide","Pfizer","gastro",180,1,"Bottle of 200ml gel"],
["Digene Gel Mint","Antacid + Antiflatulent Gel","Abbott","gastro",138,0,"Bottle of 200ml gel"],
["Digene Tablets","Antacid + Antiflatulent","Abbott","gastro",22,0,"Strip of 15 tablets"],
["Gelusil MPS","Antacid + Antiflatulent","Pfizer","gastro",130,0,"Bottle of 200ml liquid"],
["Eno Fruit Salt Lemon","Fruit Salt Antacid","Haleon","gastro",60,0,"Bottle of 100g powder"],
["Gaviscon Liquid","Sodium Alginate + Antacid","Reckitt","gastro",150,0,"Bottle of 150ml liquid"],
["Pepfiz Orange","Effervescent Digestive Enzymes","Sun Pharma","gastro",35,0,"Strip of 12 tablets"],
["Gas-O-Fast Jeera","Ayurvedic Antacid Sachet","Mankind Pharma","gastro",10,0,"Sachet of 5g"],
["Cyclopam","Dicyclomine 20mg + Paracetamol 500mg","Indoco Remedies","gastro",45,0,"Strip of 10 tablets"],
["Drotin-DS 80","Drotaverine 80mg","Walter Bushnell","gastro",95,0,"Strip of 10 tablets"],
["Ganaton 50","Itopride 50mg","Abbott","gastro",180,1,"Strip of 10 tablets"],
["Domstal 10","Domperidone 10mg","Torrent Pharmaceuticals","gastro",32,1,"Strip of 10 tablets"],
["Ondem 4","Ondansetron 4mg","Alkem Laboratories","gastro",48,1,"Strip of 10 tablets"],
["Emeset 4","Ondansetron 4mg","Cipla","gastro",42,1,"Strip of 10 tablets"],
["Avomine 25","Promethazine Teoclate 25mg","Abbott","gastro",40,0,"Strip of 10 tablets"],
["Cremaffin Plus","Liquid Paraffin + Milk of Magnesia + Sodium Picosulfate","Abbott","gastro",205,0,"Bottle of 225ml syrup"],
["Duphalac","Lactulose Solution","Abbott","gastro",280,0,"Bottle of 200ml solution"],
["Looz","Lactulose Solution","Intas Pharmaceuticals","gastro",190,0,"Bottle of 200ml solution"],
["Softovac SF","Isabgol Bowel Regulator Powder","Lupin","gastro",265,0,"Jar of 250g powder"],
["Sporlac-DS","Lactic Acid Bacillus 120M","Sanzyme","gastro",75,0,"Strip of 10 tablets"],
["Econorm 250mg","Saccharomyces Boulardii 250mg","Dr Reddy's Laboratories","gastro",63,0,"Sachet of 1g"],
["Enterogermina","Bacillus Clausii 2 Billion Spores","Sanofi","gastro",58,0,"Pack of 5x5ml vials"],
["Vizylac","Lactic Acid Bacillus + B-Complex","Torrent Pharmaceuticals","gastro",48,0,"Strip of 10 capsules"],
["Darolac","Probiotic Combination","Aristo Pharmaceuticals","gastro",85,0,"Pack of 10 sachets"],
["Lopamide","Loperamide 2mg","Torrent Pharmaceuticals","gastro",22,0,"Strip of 10 tablets"],
["Redotil 100","Racecadotril 100mg","Dr Reddy's Laboratories","gastro",120,1,"Strip of 10 capsules"],
["Zentel 400","Albendazole 400mg","GSK","gastro",12,0,"Strip of 1 tablet"],
["Bandy Plus","Albendazole 400mg + Ivermectin 6mg","Mankind Pharma","gastro",20,0,"Strip of 1 tablet"],
["Unienzyme","Fungal Diastase + Papain + Activated Charcoal","Torrent Pharmaceuticals","gastro",55,0,"Strip of 15 tablets"],
["Aristozyme Syrup","Diastase + Pepsin","Aristo Pharmaceuticals","gastro",110,0,"Bottle of 200ml syrup"],
// ---- Vitamins & Supplements ----
["Shelcal 500","Calcium 500mg + Vitamin D3 250IU","Torrent Pharmaceuticals","vitamins",110,0,"Strip of 15 tablets"],
["Shelcal-M","Calcium + Magnesium + Zinc + Vitamin D3","Torrent Pharmaceuticals","vitamins",180,0,"Strip of 15 tablets"],
["Calcimax Forte Plus","Calcium + Calcitriol + Minerals","Meyer Organics","vitamins",175,0,"Strip of 30 tablets"],
["Ostocalcium Syrup","Calcium + Vitamin D3","GSK","vitamins",130,0,"Bottle of 200ml syrup"],
["Zincovit","Multivitamin + Multimineral + Zinc","Apex Laboratories","vitamins",105,0,"Strip of 15 tablets"],
["Becosules","Vitamin B-Complex + Vitamin C","Pfizer","vitamins",38,0,"Strip of 20 capsules"],
["Zevit","B-Complex + Vitamin C + Zinc","Haleon","vitamins",42,0,"Strip of 20 capsules"],
["Cobadex CZS","B-Complex + Zinc + Selenium + Chromium","GSK","vitamins",65,0,"Strip of 15 tablets"],
["Riconia","Multivitamin + Multimineral","Aristo Pharmaceuticals","vitamins",98,0,"Strip of 10 tablets"],
["Supradyn","Multivitamin + Multimineral","Bayer","vitamins",42,0,"Strip of 15 tablets"],
["Revital H","Multivitamin + Ginseng + Minerals","Sun Pharma","vitamins",330,0,"Bottle of 30 capsules"],
["A to Z NS","Multivitamin + Multimineral","Alkem Laboratories","vitamins",105,0,"Strip of 15 tablets"],
["HealthOK","Multivitamin + Taurine + Ginseng","Mankind Pharma","vitamins",150,0,"Strip of 15 tablets"],
["Neurobion Forte","Vitamin B-Complex","P&G Health","vitamins",38,0,"Strip of 30 tablets"],
["Nurokind-Plus RF","Methylcobalamin + B-Complex","Mankind Pharma","vitamins",85,0,"Strip of 10 capsules"],
["Nurokind LC","Methylcobalamin + L-Methylfolate + Pyridoxal","Mankind Pharma","vitamins",165,0,"Strip of 10 tablets"],
["Uprise-D3 60K","Cholecalciferol 60000IU","Alkem Laboratories","vitamins",105,0,"Strip of 4 capsules"],
["Calcirol 60K Sachet","Cholecalciferol Granules 60000IU","Cadila Pharmaceuticals","vitamins",38,0,"Sachet of 1g"],
["D-Rise 60K","Cholecalciferol Oral Solution 60000IU","USV","vitamins",45,0,"Ampoule of 5ml"],
["Evion 400","Vitamin E 400mg","P&G Health","vitamins",32,0,"Strip of 10 capsules"],
["Limcee 500","Vitamin C 500mg Chewable","Abbott","vitamins",25,0,"Strip of 15 tablets"],
["Celin 500","Vitamin C 500mg","Koye Pharma","vitamins",29,0,"Strip of 20 tablets"],
["Zinconia 50","Elemental Zinc 50mg","Zuventus Healthcare","vitamins",95,0,"Strip of 15 tablets"],
["Feronia-XT","Ferrous Ascorbate + Folic Acid + Zinc","Zuventus Healthcare","vitamins",130,0,"Strip of 10 tablets"],
["Orofer-XT","Ferrous Ascorbate 100mg + Folic Acid","Emcure Pharmaceuticals","vitamins",155,0,"Strip of 10 tablets"],
["Dexorange Syrup","Iron + Vitamin B12 + Folic Acid","Franco-Indian Pharmaceuticals","vitamins",175,0,"Bottle of 200ml syrup"],
["Livogen","Ferrous Fumarate + Folic Acid","P&G Health","vitamins",45,0,"Strip of 15 tablets"],
["Vitcofol Syrup","Iron + B12 + Folic Acid","FDC Limited","vitamins",128,0,"Bottle of 150ml syrup"],
["Folvite 5mg","Folic Acid 5mg","Pfizer","vitamins",48,0,"Strip of 30 tablets"],
["Polybion LC Syrup","Vitamin B-Complex + L-Lysine","P&G Health","vitamins",120,0,"Bottle of 250ml syrup"],
["Seven Seas Original","Cod Liver Oil + Omega-3","P&G Health","vitamins",380,0,"Bottle of 60 capsules"],
["GNC Fish Oil Triple Strength","Omega-3 EPA/DHA 900mg","GNC India","vitamins",900,0,"Bottle of 60 softgels"],
["HK Vitals Biotin 10000","Biotin 10000mcg","HealthKart","vitamins",450,0,"Bottle of 60 tablets"],
["Carbamide Forte Magnesium","Magnesium Glycinate 550mg","Carbamide Forte","vitamins",480,0,"Bottle of 60 tablets"]
];
