export const SEEDS5 = [
["Sompraz 40","Esomeprazole 40mg","Sun Pharma","gastro",148,1,"Strip of 15 tablets"],
["Veloz 20","Rabeprazole 20mg","Torrent Pharmaceuticals","gastro",120,1,"Strip of 15 tablets"],
["Rifagut 400","Rifaximin 400mg","Sun Pharma","gastro",380,1,"Strip of 10 tablets"],
["Nexito 10","Escitalopram 10mg","Sun Pharma","neuro",95,1,"Strip of 10 tablets"],
["Optive Eye Drops","Carboxymethylcellulose + Glycerin","Allergan India","eye-ear",320,0,"Bottle of 10ml eye drops"],
["Sofradex Eye/Ear Drops","Framycetin + Gramicidin + Dexamethasone","Sanofi","eye-ear",130,1,"Bottle of 5ml drops"],
["Thyronorm 12.5","Thyroxine Sodium 12.5mcg","Abbott","thyroid",115,1,"Bottle of 120 tablets"],
["Thyronorm 150","Thyroxine Sodium 150mcg","Abbott","thyroid",210,1,"Bottle of 120 tablets"],
["Himalaya Gokshura","Tribulus Terrestris Extract","Himalaya Wellness","mens",160,0,"Bottle of 60 tablets"],
["Fast&Up Reload","Effervescent Electrolyte Tablets","Fast&Up","wellness",450,0,"Tube of 20 tablets"],
["Celevida Vanilla","Diabetes Care Nutrition Drink","Dr Reddy's Laboratories","wellness",690,0,"Jar of 400g powder"],
["Depura 60K","Vitamin D3 Oral Solution 60000IU","Sanofi","vitamins",48,0,"Ampoule of 5ml"],
["Maxirich","Multivitamin + Minerals Softgels","Cipla","vitamins",95,0,"Strip of 10 softgels"],
["Dolokind Plus","Aceclofenac 100mg + Paracetamol 325mg","Mankind Pharma","fever-pain",35,1,"Strip of 10 tablets"],
["Ketorol DT","Ketorolac 10mg Dispersible","Dr Reddy's Laboratories","fever-pain",115,1,"Strip of 15 tablets"],
["Gokshuradi Guggulu","Classical Urinary Wellness Formula","Baidyanath","liver-kidney",120,0,"Bottle of 80 tablets"],
["Montair 10","Montelukast 10mg","Cipla","respiratory",190,1,"Strip of 15 tablets"],
["Ventorlin Syrup","Salbutamol 2mg/5ml","GSK","respiratory",25,1,"Bottle of 100ml syrup"],
["Hicet 10","Cetirizine 10mg","Micro Labs","allergy",24,0,"Strip of 10 tablets"],
["Cepodem 200","Cefpodoxime 200mg","Sun Pharma","antibiotics",210,1,"Strip of 10 tablets"],
["Glizid 80","Gliclazide 80mg","Panacea Biotec","diabetes",68,1,"Strip of 10 tablets"],
["Nikoran 5","Nicorandil 5mg","Torrent Pharmaceuticals","cardiac",145,1,"Strip of 10 tablets"],
["Cardivas 3.125","Carvedilol 3.125mg","Sun Pharma","cardiac",95,1,"Strip of 10 tablets"],
["Cetzine Syrup","Cetirizine 5mg/5ml","Dr Reddy's Laboratories","children",35,0,"Bottle of 60ml syrup"]
];
